---

- name: get-deps | Consts
  set_fact:
      full_requirements_path: "../roles/requirements.yml"

- name: fetch galaxy roles from filtered_requirements.yml
  command: ansible-galaxy role install -r f{{ full_requirements_path }} {{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}
  register: galaxy_result
  changed_when: "'was installed successfully' in galaxy_result.stdout"
  environment:
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"