---

- name: get-deps | Consts
  set_fact:
      full_requirements_path: "../roles/requirements.yml"
      filtered_requirements: ""
- name: get-deps | Create requirments filter
  set_fact:
    requirements_filter: "[? {% for requirement in required_roles %}contains(src,'{{ requirement }}'){{ loop.last | ternary('', ' || ') }}{% endfor %}]"
  when: ( required_roles is defined )
- name: get-deps | Filter requirements
  set_fact:
    filtered_requirements: "{{ lookup('file', full_requirements_path) | from_yaml | json_query(requirements_filter) }}"
  when: ( required_roles is defined )
- name: get-deps | Write filtered requirements file for galaxy
  copy:
      content: "{{ filtered_requirements | to_nice_yaml }}"
      dest: "filtered_requirements.yml"
      mode: '666'
  when: filtered_requirements != "
- name: fetch galaxy roles from filtered_requirements.yml
  command: ansible-galaxy role install -r filtered_requirements.yml {{ ' -' + 'v' * ansible_verbosity if ansible_verbosity else '' }}
  register: galaxy_result
  when: filtered_requirements != ""
  changed_when: "'was installed successfully' in galaxy_result.stdout"
  environment:
    ANSIBLE_FORCE_COLOR: false
    GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"