---
# tasks file for ansible_main
- name: Getting Started First Playbook
  hosts: all
  tasks:
    - name: display message
      debug:
        msg: 'Script Started'

    - name: includes | loading local task
      include_tasks:
        - not_main.yml

- name: Prepare for patching
  gather_facts: no
  hosts: localhost
  vars:
    required_roles:
      - github:test
      - github:main
  tasks:
    - name: patch | Get dependencies
      include_tasks: get-deps.yml

    - name: includes | loading remote role
      include_role: 
        name: github:test

