---
# tasks file for ansible_main
- name: Getting Started First Playbook
  hosts: all
  tasks:
    - name: display message
      debug:
        msg: 'Script Started'

    - name: includes | loading local task
      include_tasks: not_main.yml

    - name: includes | loading remote role
      include_role: 
        name: github:test

