---

- name: Prepare for patching
  gather_facts: no
  hosts: localhost
  vars_files:
    - ../vars/main.yml
  vars:
    required_roles:
      - github:test
  tasks:
    - name: patch | Get dependencies
      include_tasks: ../../get-deps.yml
